### ISSUE TITLE
Obsidian shows error "Can't find heading" after triggering the popclip extension

### ISSUE THREAD

**Issue by GitVolk** [canburaks/obsidian-popclip#2]
I was happy to see that a popclip extension to directy save my (pop)clippings to my Obsidian vault.
 I am experiencing the same issue as reported here, though.
 I proceeded according to your description, thus popclip extension is accessible and I also set the options for Obsidian clipper.

![image](https://github.com/canburaks/obsidian-popclip/assets/144178326/38f7d140-0435-448e-a093-377b914cdcc0)

 WHEN I select text from a website
   AND click the O icon from the popclip menu
 THEN Obsidian throws an error "can't find heading" as explained above.

<img width="248" alt="image" src="https://github.com/canburaks/obsidian-popclip/assets/144178326/ca3518ef-324c-451c-843c-f53c9b37cf1c">

 Any idea what might be missing in the set up or how I can fix this?
 
 Many thanks in advance! 🙏🏻

_Originally posted by @GitVolk in https://github.com/canburaks/obsidian-popclip/issues/1#issuecomment-1748498409_

**Comment by canburaks** [comment]
@GitVolk what happens when you change location relative to the root directory of your obsidian vault? Because the extension sends the selection directly to the Obisidan, there is no need to pass full location.

`/` refers to the root of the vault. 

Let me know if it fixes or not.

**Comment by GitVolk** [comment]
![image](https://github.com/canburaks/obsidian-popclip/assets/144178326/b321f774-6da7-47dd-a72d-312d25c2770b)

Not sure if I got you right but replacing the full path to the vault with just the / does not change anything. 
Nothing I put in there seems so make a difference, I am afraid.
The "error message" remains the same.
(What heading is supposed to be found by the way...🤔?)

And where would the appended text be put?
Would a new note be created? Would it be appended to the daily note or to any "fixed" note that needs to be pre-created?
As an "ordinary" non-dev user I cannot figure that out from the code, I am sorry.

Any other idea what could fix the problem.

**Comment by ethanchengyu** [comment]
does it fix?
i just got the same problem

**Comment by canburaks** [comment]
The `heading` argument comes from the Popclip extension and must match the extension name. Otherwise, it causes unexpected bugs. I've added an option to disable that check. 
You can turn off the `Popclip Heading` option and test it. Please take a backup before the test.

Please let me know if it works or not. @GitVolk @ethanchengyu

**Comment by ethanchengyu** [comment]
i do not think it works
![Xnip2024-03-10_22-57-43](https://github.com/canburaks/obsidian-popclip/assets/25861044/5a893fa1-6c6f-4e01-8d8d-826e3dd8e858)

**Comment by canburaks** [comment]
@ethanchengyu What is the name of the extension in the folder? Also, on which website do you get the error?

**Comment by canburaks** [comment]
@ethanchengyu Could you update re-install the popcip extension and try with it?

```YAML
# PopClip - Obsidian extension, markdown variant 
name: ObsidianClipper 
icon: O 
capture html: true
options: 
- identifier: "vault" 
  label: "Vault name" 
  type: string
- identifier: "path"
  label: "Location"
  type: string
javascript: | 
    const vaultName = encodeURIComponent(popclip.options.vault) 
    const fileLocation = encodeURIComponent(popclip.options.path)
    const data = {
      clipping: popclip.input.markdown,
      path: fileLocation || undefined,
    }
    let clipping = popclip.input.markdown 
    if (popclip.context.browserUrl.length > 0) { // append markdown source link if available 
      data["title"] = popclip.context.browserTitle
      data["source"] = popclip.context.browserUrl
    } 
    clipping = encodeURIComponent(JSON.stringify(data))
    popclip.openUrl(`obsidian://advanced-uri?vault=${vaultName}&daily=true&data=%0A${clipping}&mode=append`) 
#end
```
